os: linux
services:
       - docker
sudo: required
language: python
env:
    global:
        - CONAN_UPLOAD=1
        - CONAN_REFERENCE="statsd-client/0.0.1"
        - CONAN_USERNAME="vthiery"
        - CONAN_CHANNEL="stable"
        - CONAN_TOTAL_PAGES=1
        - CONAN_CURRENT_PAGE=1

    matrix:
        - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
        - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
        - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
        - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
        - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
        - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1

install:
     - ./.travis/install.sh
script:
     - ./.travis/run.sh